spring.application.name=alquiler-vehiculos

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.thymeleaf.cache=false

app.jwt.secret=change-me-please-32chars-minimum-1234567890
app.jwt.expiration-ms=3600000